version: "3.8"

services:
  postgres:
    image: postgres:14
    volumes:
      - rps_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rps_api
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: rps_api_production

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: production
      RPS_API_BASE_URL: ${RPS_API_BASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NODE_ENV: production

volumes:
  rps_pgdata:
